[versions]
agp = "9.1.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.14.0"
activity = "1.13.0"
constraintlayout = "2.2.1"
recyclerview = "1.4.0"
googleServices = "4.4.2"
firebaseBom = "33.7.0"
googleid = "1.2.0"
credentialManager = "1.6.0"

okhttp = "4.12.0"
glide = "4.16.0"
zxing = "3.5.3"
maps = "19.2.0"
places = "4.4.1"
zxingEmbedded = "4.3.0"
secretsPlugin = "2.0.1"
calendar = "2.4.1"
mapbox = "10.16.2"
mpandroidchart = "v3.1.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
calendar = { group = "com.kizitonwose.calendar", name = "view", version.ref = "calendar" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore" }
firebase-storage = { group = "com.google.firebase", name = "firebase-storage" }
credentials = { group = "androidx.credentials", name = "credentials", version.ref = "credentialManager" }
credentials-play-services = { group = "androidx.credentials", name = "credentials-play-services-auth", version.ref = "credentialManager" }
googleid = { group = "com.google.android.libraries.identity.googleid", name = "googleid", version.ref = "googleid" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
zxing-core = { group = "com.google.zxing", name = "core", version.ref = "zxing" }
play-services-maps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "maps" }
places = { group = "com.google.android.libraries.places", name = "places", version.ref = "places" }
zxing-embedded = { group = "com.journeyapps", name = "zxing-android-embedded", version.ref = "zxingEmbedded" }
calendar-view = { group = "com.kizitonwose.calendar", name = "view", version.ref = "calendar" }
mapbox-maps = { group = "com.mapbox.maps", name = "android", version.ref = "mapbox" }
mpandroidchart = { group = "com.github.PhilJay", name = "MPAndroidChart", version.ref = "mpandroidchart" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
secrets-gradle = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "secretsPlugin" }

